name = "garou-interactions"
main = "index.ts"
compatibility_date = "2024-12-01"
account_id = "3314599f71a92145cd2769c61ab3edf4"

[vars]
DISCORD_PUBLIC_KEY = "638239c661b49aca1aaf6b5e646a266de4b9844260efa776fbdec8ad4ee1b383"
DISCORD_BOT_TOKEN = "MTQ4MjM4MDIzNjUyMjc4NzAwOA.G06kVH.6D2_kWssTPYvsLDUaMK_vhOH8726fxgWbaSICo"
